// ChirpStack v4 fleet codec — GENERATED by device-profiles/profile_to_decoder.py.
// Do not hand-edit; regenerate from the profiles. Decodes the ADR-005 compact payload:
// header [0]=schema [1]=device [2]=flags, then a device-specific fixed-point body (big-endian).
function decodeUplink(input) {
  var b = input.bytes;
  if (!b || b.length < 3) return { errors: ["payload too short"] };
  function u8(i)  { return b[i]; }
  function i8(i)  { var v = b[i]; return v > 0x7f ? v - 0x100 : v; }
  function u16(i) { return (b[i] << 8) | b[i + 1]; }
  function i16(i) { var v = u16(i); return v > 0x7fff ? v - 0x10000 : v; }
  function u32(i) { return (b[i] * 0x1000000) + (b[i + 1] << 16) + (b[i + 2] << 8) + b[i + 3]; }
  function i32(i) { var v = u32(i); return v > 0x7fffffff ? v - 0x100000000 : v; }
  var dev = b[1];
  var out = { schema_version: b[0], simulated: (b[2] & 0x01) !== 0, stale: (b[2] & 0x02) !== 0 };
  if (dev === 16) { // bosch-bme280
    if (b.length < 7) return { errors: ['bosch-bme280 payload short'] };
    out.device = "Bosch BME280/BMP280";
    out["temp_C"] = i16(3 + 0) / 100.0;
    out["pressure_hPa"] = u16(3 + 2) / 10.0;
    return { data: out };
  }
  return { errors: ["unknown device type 0x" + dev.toString(16)] };
}

function encodeDownlink(input) { return { bytes: [] }; }
