#!/usr/bin/env python3
"""profile_to_decoder.py — generate a ChirpStack v4 codec from the device profiles (ADR-006).

Symmetric partner to profile_to_blob.py: that emits the NVS blob a node consumes; this emits the
JS `decodeUplink` the CRM installs so the ADR-005 frames those nodes send decode to engineering
units. One combined codec branches on the payload device byte across all profiles.

  python3 profile_to_decoder.py                 # all profiles/*.json -> fleet codec on stdout
  python3 profile_to_decoder.py -o out.js        # write to a file

The decode math mirrors the payload field table exactly (offset + encoding + scale); field keys and
units come from the matching measurand. Regenerate whenever a profile's payload changes.
"""
import argparse
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# big-endian readers; payload offsets are body-relative, so the codec adds the 3-byte header.
READER = {"u8": "u8", "i8": "i8", "u16": "u16", "i16": "i16", "u32": "u32", "i32": "i32"}


def device_branch(doc: dict) -> str:
    dev = doc["device"]["type_byte"]
    pl = doc["payload"]
    name = doc["device"]["model"]
    units = {m["key"]: m.get("unit", "") for m in doc["measurands"]}
    lines = [f"  if (dev === {dev}) {{ // {doc['profile_id']}"]
    lines.append(f"    if (b.length < {pl['total_len']}) return {{ errors: ['{doc['profile_id']} payload short'] }};")
    lines.append(f"    out.device = {json.dumps(name)};")
    for f in pl["fields"]:
        rd = READER[f["encoding"]]
        scale = f["scale"]
        unit = units.get(f["key"], "")
        key = f["key"] + (("_" + unit) if unit and unit.isalnum() else "")
        expr = f"{rd}(3 + {f['offset']})"
        if scale != 1:
            expr = f"{expr} / {scale}"
        lines.append(f"    out[{json.dumps(key)}] = {expr};")
    lines.append("    return { data: out };")
    lines.append("  }")
    return "\n".join(lines)


def build(profiles: list) -> str:
    branches = "\n".join(device_branch(json.loads(open(p).read())) for p in profiles)
    return f"""// ChirpStack v4 fleet codec — GENERATED by device-profiles/profile_to_decoder.py.
// Do not hand-edit; regenerate from the profiles. Decodes the ADR-005 compact payload:
// header [0]=schema [1]=device [2]=flags, then a device-specific fixed-point body (big-endian).
function decodeUplink(input) {{
  var b = input.bytes;
  if (!b || b.length < 3) return {{ errors: ["payload too short"] }};
  function u8(i)  {{ return b[i]; }}
  function i8(i)  {{ var v = b[i]; return v > 0x7f ? v - 0x100 : v; }}
  function u16(i) {{ return (b[i] << 8) | b[i + 1]; }}
  function i16(i) {{ var v = u16(i); return v > 0x7fff ? v - 0x10000 : v; }}
  function u32(i) {{ return (b[i] * 0x1000000) + (b[i + 1] << 16) + (b[i + 2] << 8) + b[i + 3]; }}
  function i32(i) {{ var v = u32(i); return v > 0x7fffffff ? v - 0x100000000 : v; }}
  var dev = b[1];
  var out = {{ schema_version: b[0], simulated: (b[2] & 0x01) !== 0, stale: (b[2] & 0x02) !== 0 }};
{branches}
  return {{ errors: ["unknown device type 0x" + dev.toString(16)] }};
}}

function encodeDownlink(input) {{ return {{ bytes: [] }}; }}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a ChirpStack codec from the device profiles.")
    ap.add_argument("-o", "--out", help="output file (default: stdout)")
    args = ap.parse_args()
    profiles = sorted(glob.glob(os.path.join(HERE, "profiles", "*.json")))
    if not profiles:
        sys.exit("no profiles found")
    js = build(profiles)
    if args.out:
        open(args.out, "w").write(js)
        print(f"wrote {args.out} ({len(profiles)} devices)", file=sys.stderr)
    else:
        sys.stdout.write(js)
    return 0


if __name__ == "__main__":
    sys.exit(main())
